### ISSUE TITLE
Update as deprecated?

### ISSUE THREAD

**Issue by HParker** [krisajenkins/helm-spotify#5]
Perhaps I am doing something wrong or perhaps Spotify has changed their api, but naïvely pulling this project and launching it doesn't seem to work for me. No errors just nothing in the helm buffer.

if the project is still working and it is me, let me know.
Otherwise can we update the status header in the readme?

**Comment by hagleitn** [comment]
You need to have spotify installed otherwise you get that -2740 error.

**Comment by HParker** [comment]
@hagleitn Ah! thank you.
