### ISSUE TITLE
Syntax Error on helm-spotify

### ISSUE THREAD

**Issue by bolivier** [krisajenkins/helm-spotify#8]
I can get the list, but when I select one with return, the track doesn't play and the minibuffer messages me `"30:40: syntax error: A identifier can't go after this identifier. (-2740)"`

next, previous, play, pause, and playpause also don't interact with spotify

**Comment by sergio101** [comment]
this is the error that i'm getting: 

2015-03-26 15:28:13.220 osascript[28494:1729298] Error loading /Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types:  dlopen(/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types, 262): no suitable image found.  Did find:
	/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types: no matching architecture in universal wrapper
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" declares no loadable handlers.
30:40: syntax error: A identifier can’t go after this identifier. (-2740)

**Comment by bolivier** [comment]
I'm not sure why, but it's gone now.  Was there an update?
